[2024-06-10T15:22:06.440-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-10T15:22:06.452-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.extract_csv manual__2024-06-10T18:21:58.711921+00:00 [queued]>
[2024-06-10T15:22:06.456-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.extract_csv manual__2024-06-10T18:21:58.711921+00:00 [queued]>
[2024-06-10T15:22:06.456-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-10T15:22:06.467-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_csv> on 2024-06-10 18:21:58.711921+00:00
[2024-06-10T15:22:06.469-0300] {standard_task_runner.py:63} INFO - Started process 7681 to run task
[2024-06-10T15:22:06.471-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline', 'extract_csv', 'manual__2024-06-10T18:21:58.711921+00:00', '--job-id', '1088', '--raw', '--subdir', 'DAGS_FOLDER/dag_extracao_daily.py', '--cfg-path', '/tmp/tmpjr8wcks4']
[2024-06-10T15:22:06.472-0300] {standard_task_runner.py:91} INFO - Job 1088: Subtask extract_csv
[2024-06-10T15:22:06.497-0300] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline.extract_csv manual__2024-06-10T18:21:58.711921+00:00 [running]> on host Pedro-Conrado
[2024-06-10T15:22:06.546-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='extract_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-06-10T18:21:58.711921+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-10T18:21:58.711921+00:00'
[2024-06-10T15:22:06.547-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-10T15:22:06.547-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-10T15:22:06.548-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/pedro/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/pedro/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/pedro/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/pedro/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/pedro/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/pedro/airflow/dags/dag_extracao_daily.py", line 49, in extract_csv
    shutil.copy(input_file, output_file)
  File "/usr/lib/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'airflow/data/csv/order_details.csv'
[2024-06-10T15:22:06.550-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=data_pipeline, task_id=extract_csv, run_id=manual__2024-06-10T18:21:58.711921+00:00, execution_date=20240610T182158, start_date=20240610T182206, end_date=20240610T182206
[2024-06-10T15:22:06.558-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 1088 for task extract_csv ([Errno 2] No such file or directory: 'airflow/data/csv/order_details.csv'; 7681)
[2024-06-10T15:22:06.603-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-10T15:22:06.624-0300] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-10T15:22:06.631-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
